version: "2"
services:

  digdag:
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "4440:4440"
    volumes:
      - data:/digdag-work

volumes:
  data:
    driver: local
